/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicWorkerRulesRouteImport } from './routes/api/public/worker/rules'
import { Route as ApiPublicWorkerLogsRouteImport } from './routes/api/public/worker/logs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWorkerRulesRoute = ApiPublicWorkerRulesRouteImport.update({
  id: '/api/public/worker/rules',
  path: '/api/public/worker/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWorkerLogsRoute = ApiPublicWorkerLogsRouteImport.update({
  id: '/api/public/worker/logs',
  path: '/api/public/worker/logs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/worker/logs': typeof ApiPublicWorkerLogsRoute
  '/api/public/worker/rules': typeof ApiPublicWorkerRulesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/worker/logs': typeof ApiPublicWorkerLogsRoute
  '/api/public/worker/rules': typeof ApiPublicWorkerRulesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/worker/logs': typeof ApiPublicWorkerLogsRoute
  '/api/public/worker/rules': typeof ApiPublicWorkerRulesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/worker/logs' | '/api/public/worker/rules'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/worker/logs' | '/api/public/worker/rules'
  id: '__root__' | '/' | '/api/public/worker/logs' | '/api/public/worker/rules'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicWorkerLogsRoute: typeof ApiPublicWorkerLogsRoute
  ApiPublicWorkerRulesRoute: typeof ApiPublicWorkerRulesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker/rules': {
      id: '/api/public/worker/rules'
      path: '/api/public/worker/rules'
      fullPath: '/api/public/worker/rules'
      preLoaderRoute: typeof ApiPublicWorkerRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker/logs': {
      id: '/api/public/worker/logs'
      path: '/api/public/worker/logs'
      fullPath: '/api/public/worker/logs'
      preLoaderRoute: typeof ApiPublicWorkerLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicWorkerLogsRoute: ApiPublicWorkerLogsRoute,
  ApiPublicWorkerRulesRoute: ApiPublicWorkerRulesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
