/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppWorkerRouteImport } from './routes/_authenticated/app.worker'
import { Route as AuthenticatedAppLogsRouteImport } from './routes/_authenticated/app.logs'
import { Route as AuthenticatedAppLoginRouteImport } from './routes/_authenticated/app.login'
import { Route as AuthenticatedAppChannelsRouteImport } from './routes/_authenticated/app.channels'
import { Route as ApiPublicWorkerRulesRouteImport } from './routes/api/public/worker/rules'
import { Route as ApiPublicWorkerLogsRouteImport } from './routes/api/public/worker/logs'
import { Route as ApiPublicWorkerLoginStatusRouteImport } from './routes/api/public/worker/login-status'
import { Route as ApiPublicWorkerLoginStateRouteImport } from './routes/api/public/worker/login-state'
import { Route as ApiPublicWorkerHeartbeatRouteImport } from './routes/api/public/worker/heartbeat'
import { Route as ApiPublicWorkerChannelsRouteImport } from './routes/api/public/worker/channels'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppWorkerRoute = AuthenticatedAppWorkerRouteImport.update({
  id: '/worker',
  path: '/worker',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppLogsRoute = AuthenticatedAppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppLoginRoute = AuthenticatedAppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppChannelsRoute =
  AuthenticatedAppChannelsRouteImport.update({
    id: '/channels',
    path: '/channels',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const ApiPublicWorkerRulesRoute = ApiPublicWorkerRulesRouteImport.update({
  id: '/api/public/worker/rules',
  path: '/api/public/worker/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWorkerLogsRoute = ApiPublicWorkerLogsRouteImport.update({
  id: '/api/public/worker/logs',
  path: '/api/public/worker/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWorkerLoginStatusRoute =
  ApiPublicWorkerLoginStatusRouteImport.update({
    id: '/api/public/worker/login-status',
    path: '/api/public/worker/login-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWorkerLoginStateRoute =
  ApiPublicWorkerLoginStateRouteImport.update({
    id: '/api/public/worker/login-state',
    path: '/api/public/worker/login-state',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWorkerHeartbeatRoute =
  ApiPublicWorkerHeartbeatRouteImport.update({
    id: '/api/public/worker/heartbeat',
    path: '/api/public/worker/heartbeat',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWorkerChannelsRoute = ApiPublicWorkerChannelsRouteImport.update({
  id: '/api/public/worker/channels',
  path: '/api/public/worker/channels',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/channels': typeof AuthenticatedAppChannelsRoute
  '/app/login': typeof AuthenticatedAppLoginRoute
  '/app/logs': typeof AuthenticatedAppLogsRoute
  '/app/worker': typeof AuthenticatedAppWorkerRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/api/public/worker/channels': typeof ApiPublicWorkerChannelsRoute
  '/api/public/worker/heartbeat': typeof ApiPublicWorkerHeartbeatRoute
  '/api/public/worker/login-state': typeof ApiPublicWorkerLoginStateRoute
  '/api/public/worker/login-status': typeof ApiPublicWorkerLoginStatusRoute
  '/api/public/worker/logs': typeof ApiPublicWorkerLogsRoute
  '/api/public/worker/rules': typeof ApiPublicWorkerRulesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/channels': typeof AuthenticatedAppChannelsRoute
  '/app/login': typeof AuthenticatedAppLoginRoute
  '/app/logs': typeof AuthenticatedAppLogsRoute
  '/app/worker': typeof AuthenticatedAppWorkerRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/api/public/worker/channels': typeof ApiPublicWorkerChannelsRoute
  '/api/public/worker/heartbeat': typeof ApiPublicWorkerHeartbeatRoute
  '/api/public/worker/login-state': typeof ApiPublicWorkerLoginStateRoute
  '/api/public/worker/login-status': typeof ApiPublicWorkerLoginStatusRoute
  '/api/public/worker/logs': typeof ApiPublicWorkerLogsRoute
  '/api/public/worker/rules': typeof ApiPublicWorkerRulesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/channels': typeof AuthenticatedAppChannelsRoute
  '/_authenticated/app/login': typeof AuthenticatedAppLoginRoute
  '/_authenticated/app/logs': typeof AuthenticatedAppLogsRoute
  '/_authenticated/app/worker': typeof AuthenticatedAppWorkerRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/api/public/worker/channels': typeof ApiPublicWorkerChannelsRoute
  '/api/public/worker/heartbeat': typeof ApiPublicWorkerHeartbeatRoute
  '/api/public/worker/login-state': typeof ApiPublicWorkerLoginStateRoute
  '/api/public/worker/login-status': typeof ApiPublicWorkerLoginStatusRoute
  '/api/public/worker/logs': typeof ApiPublicWorkerLogsRoute
  '/api/public/worker/rules': typeof ApiPublicWorkerRulesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/app/channels'
    | '/app/login'
    | '/app/logs'
    | '/app/worker'
    | '/app/'
    | '/api/public/worker/channels'
    | '/api/public/worker/heartbeat'
    | '/api/public/worker/login-state'
    | '/api/public/worker/login-status'
    | '/api/public/worker/logs'
    | '/api/public/worker/rules'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/channels'
    | '/app/login'
    | '/app/logs'
    | '/app/worker'
    | '/app'
    | '/api/public/worker/channels'
    | '/api/public/worker/heartbeat'
    | '/api/public/worker/login-state'
    | '/api/public/worker/login-status'
    | '/api/public/worker/logs'
    | '/api/public/worker/rules'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/app/channels'
    | '/_authenticated/app/login'
    | '/_authenticated/app/logs'
    | '/_authenticated/app/worker'
    | '/_authenticated/app/'
    | '/api/public/worker/channels'
    | '/api/public/worker/heartbeat'
    | '/api/public/worker/login-state'
    | '/api/public/worker/login-status'
    | '/api/public/worker/logs'
    | '/api/public/worker/rules'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicWorkerChannelsRoute: typeof ApiPublicWorkerChannelsRoute
  ApiPublicWorkerHeartbeatRoute: typeof ApiPublicWorkerHeartbeatRoute
  ApiPublicWorkerLoginStateRoute: typeof ApiPublicWorkerLoginStateRoute
  ApiPublicWorkerLoginStatusRoute: typeof ApiPublicWorkerLoginStatusRoute
  ApiPublicWorkerLogsRoute: typeof ApiPublicWorkerLogsRoute
  ApiPublicWorkerRulesRoute: typeof ApiPublicWorkerRulesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/worker': {
      id: '/_authenticated/app/worker'
      path: '/worker'
      fullPath: '/app/worker'
      preLoaderRoute: typeof AuthenticatedAppWorkerRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/logs': {
      id: '/_authenticated/app/logs'
      path: '/logs'
      fullPath: '/app/logs'
      preLoaderRoute: typeof AuthenticatedAppLogsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/login': {
      id: '/_authenticated/app/login'
      path: '/login'
      fullPath: '/app/login'
      preLoaderRoute: typeof AuthenticatedAppLoginRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/channels': {
      id: '/_authenticated/app/channels'
      path: '/channels'
      fullPath: '/app/channels'
      preLoaderRoute: typeof AuthenticatedAppChannelsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/worker/rules': {
      id: '/api/public/worker/rules'
      path: '/api/public/worker/rules'
      fullPath: '/api/public/worker/rules'
      preLoaderRoute: typeof ApiPublicWorkerRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker/logs': {
      id: '/api/public/worker/logs'
      path: '/api/public/worker/logs'
      fullPath: '/api/public/worker/logs'
      preLoaderRoute: typeof ApiPublicWorkerLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker/login-status': {
      id: '/api/public/worker/login-status'
      path: '/api/public/worker/login-status'
      fullPath: '/api/public/worker/login-status'
      preLoaderRoute: typeof ApiPublicWorkerLoginStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker/login-state': {
      id: '/api/public/worker/login-state'
      path: '/api/public/worker/login-state'
      fullPath: '/api/public/worker/login-state'
      preLoaderRoute: typeof ApiPublicWorkerLoginStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker/heartbeat': {
      id: '/api/public/worker/heartbeat'
      path: '/api/public/worker/heartbeat'
      fullPath: '/api/public/worker/heartbeat'
      preLoaderRoute: typeof ApiPublicWorkerHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker/channels': {
      id: '/api/public/worker/channels'
      path: '/api/public/worker/channels'
      fullPath: '/api/public/worker/channels'
      preLoaderRoute: typeof ApiPublicWorkerChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppChannelsRoute: typeof AuthenticatedAppChannelsRoute
  AuthenticatedAppLoginRoute: typeof AuthenticatedAppLoginRoute
  AuthenticatedAppLogsRoute: typeof AuthenticatedAppLogsRoute
  AuthenticatedAppWorkerRoute: typeof AuthenticatedAppWorkerRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppChannelsRoute: AuthenticatedAppChannelsRoute,
  AuthenticatedAppLoginRoute: AuthenticatedAppLoginRoute,
  AuthenticatedAppLogsRoute: AuthenticatedAppLogsRoute,
  AuthenticatedAppWorkerRoute: AuthenticatedAppWorkerRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicWorkerChannelsRoute: ApiPublicWorkerChannelsRoute,
  ApiPublicWorkerHeartbeatRoute: ApiPublicWorkerHeartbeatRoute,
  ApiPublicWorkerLoginStateRoute: ApiPublicWorkerLoginStateRoute,
  ApiPublicWorkerLoginStatusRoute: ApiPublicWorkerLoginStatusRoute,
  ApiPublicWorkerLogsRoute: ApiPublicWorkerLogsRoute,
  ApiPublicWorkerRulesRoute: ApiPublicWorkerRulesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
